### PR TITLE
ES6/ESM Changes

### PR DESCRIPTION
**Pull request by brettz9**
- Breaking change: Move `getHelpXML` instance method to more accurate class
    method `getHelpList`
- Breaking change (Browser): Move `index.js` (to `src/index.js` with build in `dist`)
- Breaking change (Node): Require Node > 4.0.0 (using `Object.assign`)
- Enhancement: Offer ESM, babelified distributions (minified and full)
  along with UMD, based on ES6 source through Rollup
- Linting (Markdown): Brackets around links
- Linting (ESLint): Add ESLint
- Linting (package.json): Add recommended fields
- npm: Add npm-recommended `package-lock.json`
- Docs: Use modern features in examples
- Testing: Add basic test
- npm: Bump to 2.0.0

### CODE REVIEW

**Comment by brettz9** [comment]
Hi, @yetzt... Are you still maintaining this project?

**Comment by yetzt** [comment]
hey @brettz9,

good question, since this is not my code in the first place. 

i'm uncertain if its a good idea to introduce breakign changes in this code, since it might be used in old browsers or with old versions of node or other js enviroments. i'd recommend to make an explicit fork if you feel that you require your code do be all es6.

**Comment by brettz9** [comment]
Actually, the breaking changes are not related to ES6 per se.

Besides the unrelated `getHelpXML` and Node changes (which I could undo), it is only breaking in the sense that I thought it reasonable to change the path of where the non-ES6 code would be placed. I could instead, however, keep the distribution at `/index.js` so that it was not a breaking change and just have the source in `src` (from which it would get compiled to the non-ES6 version at `/index.js`).

**Comment by brettz9** [comment]
Can I undo the `getHelpXML` breaking change, and if you wish the Node breaking change and path breaking change, so I can get this merged?

**Pull request closed without merging**
