### PR TITLE
Fixed issue with regex

### PR DESCRIPTION
**Pull request by pushpagarwal**
Original code had issue with regex for detecting hash value. It was using \w which is true for non-hex digits alphabets g-z also. Changed it to [0-9a-f] it covers all the hex digits.

### CODE REVIEW

**Comment by pushpagarwal** [comment]
To reproduce original issue test string "random" or any 6 character string or 3 character string. 
Can be tested easily at http://www.phpied.com/files/rgbcolor/rgbcolor.html

**Comment by yetzt** [comment]
@pushpagarwal i fixed your regex to be case insensitive, lot of people use upper case hex values and `parseInt` handles them just fine.

**Comment by pushpagarwal** [comment]
@yetzt I had used lowercase in regex since input has been already converted to lowercase at line#16 color_string = color_string.toLowerCase(); 
I had tested it with uppercase hex colors.

**Comment by yetzt** [comment]
ah well, thanks for the improvement anyway. :)

**Pull request merged**
